### PR TITLE
Enable Travis builds

### PR DESCRIPTION
**Pull request by mmdriley**
Add builds for:
- Linux/clang
- Linux/gcc
- macOS/clang
- Windows/msvc

### CODE REVIEW

**Comment by asteinha** [comment]
LGTM, just fix the travis tests first.

**Comment by asteinha** [comment]
Ideally it might be convenient to build them separately with -m32 and across optimization levels, so that we find breaking changes as soon as possible.

**Comment by mmdriley** [comment]
Agree we'll want to add more dimensions for 32/64 bit and optimization level. But I think this is in a good place to submit now that we get coverage on different compilers and OSes:

image

Also nice-to-have: different architectures.

**Comment by mmdriley** [comment]
@asteinha thanks for the early feedback. All builds are now green. Please take another look and comment/approve?

**Review by asteinha — APPROVED** [review]
LGTM. We might want to extend it eventually to test it with different optimization levels and 32bits vs. 64bits, but as the first version it's perfect - especially the coverage that we won't have to start Windows and MacOS each time.

**Pull request merged**
