### PR TITLE
Move build files, fix issues, add comments

### PR DESCRIPTION
**Pull request by mmdriley**
Move the demo targets into `CMakeLists.txt` in the `demos` directory

Add a comment in `.gitignore` about why we're ignoring the `build`
directory

Change the `kmod` build so it doesn't put build outputs in the source
tree and stops modifying `kmod/Makefile`

Instead of setting the CMake build type, just make sure we add the
one flag we need to avoid a known bug.

Add more comments throughout

### CODE REVIEW

**Comment by asteinha** [comment]
This breaks the build on Windows and MSVC:
------ Build started: Project: spectre_v1, Configuration: Debug x64 ------
Building Custom Rule C:/Users/asteinhauser/Desktop/safeside-mattdr-build-tweaks/demos/CMakeLists.txt
cl : Command line error D8016 : '/O1' and '/RTC1' command-line options are incompatible
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(429,5): error MSB6006: "CL.exe" exited with code 2.
Done building project "spectre_v1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by mmdriley** [comment]
Rebased on #28 so I can see+debug the build failure.

**Comment by mmdriley** [comment]
Thanks for catching the MSVC break. I believe I've fixed it and the Travis Windows/MSVC build is green.

**Review by asteinha — APPROVED** [review]
Good work.

**Pull request merged**
